export const schemaVersion = 18;

export const syncStatusValues = ["local", "pending", "synced", "failed"] as const;

export const resettableTables = [
  "sale_supply_lot_usages",
  "sale_supply_usages",
  "supply_usage_rules",
  "sale_product_lot_usages",
  "stock_adjustment_allocations",
  "stock_adjustments",
  "production_input_allocations",
  "production_plan_allocations",
  "production_plan_requirements",
  "production_plan_stages",
  "production_plans",
  "recipe_draft_lines",
  "recipe_drafts",
  "catalog_item_recipe_roles",
  "problem_reports",
  "offline_queue",
  "receipt_records",
  "owner_alerts",
  "sale_ingredient_usages",
  "product_transfers",
  "fixed_cost_payments",
  "fixed_costs",
  "production_ingredient_usages",
  "product_stock_lots",
  "production_batches",
  "recipe_version_cost_summaries",
  "recipe_version_lines",
  "catalog_cost_profiles",
  "recipe_versions",
  "recipe_batches",
  "recipe_ingredient_lines",
  "recipes",
  "ingredient_movements",
  "ingredient_lots",
  "purchase_receipts",
  "suppliers",
  "item_unit_conversions",
  "legacy_item_bindings",
  "catalog_items",
  "ingredients",
  "inventory_movements",
  "sale_items",
  "sales",
  "products",
  "branches",
  "businesses",
  "app_settings",
] as const;

export const countableTables = [
  "problem_reports",
  "catalog_items",
  "recipe_drafts",
  "production_plans",
  "stock_adjustments",
  "businesses",
  "branches",
  "products",
  "sales",
  "inventory_movements",
  "recipe_batches",
  "owner_alerts",
  "receipt_records",
  "offline_queue",
  "ingredients",
  "ingredient_lots",
  "ingredient_movements",
  "recipes",
  "recipe_ingredient_lines",
  "production_batches",
  "production_ingredient_usages",
  "sale_ingredient_usages",
  "product_transfers",
  "fixed_costs",
  "fixed_cost_payments",
] as const;

export type ResettableTable = (typeof resettableTables)[number];
export type CountableTable = (typeof countableTables)[number];
export type LocalDataCounts = Record<CountableTable, number>;
